### ISSUE TITLE
数据库连不上

### ISSUE THREAD

**Issue by SuperReck** [84960390/vue-book-manage#1]
求解

**Comment by SuperReck** [comment]
数据库的问题，版本太新了
https://blog.csdn.net/qq_36068954/article/details/80175755

**Comment by yhforever** [comment]
运行mysql文件一直报错，不知道怎么回事，用的是navicat

**Comment by 84960390** [comment]
> 运行mysql文件一直报错，不知道怎么回事，用的是navicat
运行sql文件的时候，把编码方式改为utf-8试试

**Comment by yhforever** [comment]
解决了，navicat版本问题，要改一下sql文件编码格式
